### ISSUE TITLE
App won't load - Cannot read property 'storefrontAccessToken' of null

### ISSUE THREAD

**Issue by apblbl** [Shopify/shopify-marketplaces-admin-app#1]
Error:

`
┃ TypeError: Cannot read property 'storefrontAccessToken' of null

Error object inside Response:

` [
┃   {
┃     message: 'StorefrontAccessTokenCreate access denied',
┃     locations: [ [Object] ],
┃     path: [ 'storefrontAccessTokenCreate' ]
┃   }
┃ ]`

I am using the following scopes : - 

`SCOPES=write_products,write_customers,write_draft_orders,unauthenticated_read_product_listings,read_product_listings`

I followed all the steps given at [https://shopify.dev/marketplaces/getting-started/get-started-with-shopify-marketplace-kit](https://shopify.dev/marketplaces/getting-started/get-started-with-shopify-marketplace-kit)

**Comment by SerhiDi** [comment]
I have the same error after cloning this repo.
Again, Shopify has the worst documentation I've ever seen. I find the same small errors in almost every article.

Shopify dev or writers missing few steps, requirement steps:
- You must **create** a **PUBLIC** app. The only public app has a sales channel option.
- Open app setup. **Turn your app into a sales channel**.

If you use Shopify apps for the first time your brain might explode, this documentation will confuse you. 
Shopify devs, please, don't reply to this message. Just update your documentation. Shame on you.
