### ISSUE TITLE
[BUG]: UI is not showing

### ISSUE THREAD

**Issue by devRaunakYadav** [Shopify/shopify-marketplaces-admin-app#15]
![image](https://user-images.githubusercontent.com/86884638/170416142-45e3fb85-bbb9-4b0b-b503-9b6c4602d04e.png)

I have done all things successfully but the app UI not showing, I'm trying all browsers still UI does not show
App run smoothly not a single error show but I don't know why UI not showing

**Comment by misshula** [comment]
can you share your console logs?

**Comment by devRaunakYadav** [comment]
![image](https://user-images.githubusercontent.com/86884638/170627187-fac0da5c-e951-4ab2-bde3-a649dab81321.png)

please check @misshula

**Comment by devRaunakYadav** [comment]
![image](https://user-images.githubusercontent.com/86884638/170632197-dff2cc02-3760-4dd9-96d7-f7c422f0196c.png)

**Comment by devRaunakYadav** [comment]
> can you share your console logs?

Hey @misshula  I have shared error please check
