### ISSUE TITLE
Issues on admin shop

### ISSUE THREAD

**Issue by devRaunakYadav** [Shopify/shopify-marketplaces-admin-app#16]
![image](https://user-images.githubusercontent.com/86884638/171975691-bc7cdfcb-d34d-4e8f-8355-6ddc5c01caa5.png)
please check this issue why it's come, I have tried many time to fix it but it's not.

**Comment by thingsyvonnecreates** [comment]
I have the same issues also. Please help!

**Comment by devRaunakYadav** [comment]
@misshula can you please check it??
