### ISSUE TITLE
App doesn't run

### ISSUE THREAD

**Issue by cma93** [Shopify/shopify-marketplaces-admin-app#28]
Hi, I tried to run the app on localhost but its packages has many dependency conflicts and if somehow you manage to install it and run it then store doesn't show anything at all. The Link will take you to the blank page. (Not even Shopify's admin will show up). Tried many things but still the same results. Sometimes, app installation page in shopify admin shows up and after that it goes blank. But this repository needs upgradation (usage notes and code).

**Update:**

Managed to run it after resolving conflicts but then it also has some authentication problem.

When you run it locally: if you start it like my-app-url.com/login?shop=my-store.com it works and lands you on the page where you can install the app. But if you try to install the app directly from apps -> select store -> development store then, you get **"There’s no page at this address"**  error. So, I can't install it on a store after deployment.

**Comment by Karen-boop** [comment]
Hi there! Thanks for reaching out. Can you please confirm that you have done all steps in the [Getting started](https://shopify.dev/marketplaces/getting-started#build-requirements) guide including turning your app into a [Sales Channel?](https://shopify.dev/apps/channels#sales-channel-app-requirements)

**Comment by cma93** [comment]
Yes, I have.

**Comment by Karen-boop** [comment]
Continuing conversation here as PR is merged. 

https://github.com/Shopify/shopify-marketplaces-admin-app/pull/30#issuecomment-1276653569

> Then how you can install it on deployment server if you build something using this as a base?

> If it's deployed on the server (in production) even then you can't install it on dev stores

This repo is meant as a starting point for Partners to create their own marketplace sales channel apps. It bundles up the set-up code and complements the [Marketplace Kit tutorials](https://shopify.dev/marketplaces). When a partners app is complete and ready to deploy and distribute the process is the same for any other Shopify app. There are some resources below which will help you out with deployment and distribution:

[Channel app requirements](https://shopify.dev/apps/channels#sales-channel-app-requirements)
[Deployment](https://shopify.dev/apps/deployment/web)
[Development store restrictions](https://shopify.dev/apps/tools/development-stores#features-and-limitations-of-development-stores)
[Tutorial](https://www.shopify.com/ca/partners/blog/how-to-build-a-shopify-app) for the entire app creation process:
[Article](https://community.shopify.com/c/shopify-apps/what-is-the-process-to-deploy-an-app-for-production/td-p/1587680) about deploying an app for production.

There is further reading and resources  on [shopify.dev/apps](https://shopify.dev/apps)

**Comment by cma93** [comment]
So, that means this app as it is won't be able to work in production mode. I mean if someone build their partner app using this as a base it will fail to install only but the other procedures would work like OAutth. Right?

**Comment by cma93** [comment]
In simple words, this app can't be used as a base for app development if you want to deploy it in production.

**Comment by cma93** [comment]
In this case, I think it should be mentioned in Readme file.

**Comment by Karen-boop** [comment]
> So, that means this app as it is won't be able to work in production mode. I mean if someone build their partner app using this as a base it will fail to install only but the other procedures would work like OAutth. Right?

> In simple words, this app can't be used as a base for app development if you want to deploy it in production.

No this is not the case. This app can be used as a starting point for your own marketplace app. You will need to customize the code, add other pages, links to your buyer-facing marketplace, host the app and go through the app review process to get your app listed on the app store for merchants to install once your app is complete.

The links shared above are a great source of information and [this in particular](https://shopify.dev/apps/getting-started)  explains how apps work on shopify and is a good overview.

**Comment by cma93** [comment]
> > So, that means this app as it is won't be able to work in production mode. I mean if someone build their partner app using this as a base it will fail to install only but the other procedures would work like OAutth. Right?
> 
> > In simple words, this app can't be used as a base for app development if you want to deploy it in production.
> 
> No this is not the case. This app can be used as a starting point for your own marketplace app. You will need to customize the code, add other pages, links to your buyer-facing marketplace, host the app and go through the app review process to get your app listed on the app store for merchants to install once your app is complete.
> 
> The links shared above are a great source of information and [this in particular](https://shopify.dev/apps/getting-started) explains how apps work on shopify and is a good overview.

Well, I understand that but I meant like using it as a boiler plate for the app. For example, If you submit it for the review the first problem that would arise is: App can't be installed directly from the dashboard.
Then, second problem is #32 and then there might be some other problems as well like "App must verify the authenticity of the request from Shopify".

I know these issues because we used this as a starting point (thinking that all the OAuth and best practices would be covered) but we got these issues reported by review team. 

There might be more issues but that's how far I could get until now.

**Comment by cma93** [comment]
@Karen-boop would you comment on this?

**Comment by Karen-boop** [comment]
Thanks for the feedback! Providing this kind of info is really helpful for us to improve the repo. If you want to list out any other issues you had with getting the app reviewed apart from those above we can take them onboard.
